export const browserCoreExamples = [
  "orionclaw browser status",
  "orionclaw browser start",
  "orionclaw browser stop",
  "orionclaw browser tabs",
  "orionclaw browser open https://example.com",
  "orionclaw browser focus abcd1234",
  "orionclaw browser close abcd1234",
  "orionclaw browser screenshot",
  "orionclaw browser screenshot --full-page",
  "orionclaw browser screenshot --ref 12",
  "orionclaw browser snapshot",
  "orionclaw browser snapshot --format aria --limit 200",
  "orionclaw browser snapshot --efficient",
  "orionclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "orionclaw browser navigate https://example.com",
  "orionclaw browser resize 1280 720",
  "orionclaw browser click 12 --double",
  'orionclaw browser type 23 "hello" --submit',
  "orionclaw browser press Enter",
  "orionclaw browser hover 44",
  "orionclaw browser drag 10 11",
  "orionclaw browser select 9 OptionA OptionB",
  "orionclaw browser upload /tmp/orionclaw/uploads/file.pdf",
  'orionclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "orionclaw browser dialog --accept",
  'orionclaw browser wait --text "Done"',
  "orionclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "orionclaw browser console --level error",
  "orionclaw browser pdf",
];
